{
 "title": "PriceWatch Operations",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "label_values(service_name)" }
  ]
 },
 "panels": [
  { "title": "Business", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Products Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(products_created_total)" }
   ]
  },
  {
   "title": "New Products per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(products_created_total[5m])) * 60"
    }
   ]
  },
  {
   "title": "API RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service_name=~\"$service\"}[5m])) by (http_method)"
    }
   ]
  },
  {
   "title": " API Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service_name=~\"$service\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_status_code=~\"5.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Tasks Processed / Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(price_update_tasks_processed_total{service_name=~\"$service\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Scrape Duration ",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(price_update_scrape_duration_seconds_bucket{service_name=~\"$service\"}[5m])) by (le)"
    }
   ]
  },
  {
   "title": " DB Transactions / Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{datname=\"pricewatch_db\"}[5m]) + irate(pg_stat_database_xact_rollback{datname=\"pricewatch_db\"}[5m])"
    }
   ]
  },
  {
   "title": "DB Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"pricewatch_db\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "RabbitMQ Queue Depth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready)"
    }
   ]
  },
  {
   "title": "RabbitMQ Consumer Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rabbitmq_queue_consumers)" }
   ]
  }
 ]
}