# Generated by Django 6.0 on 2025-12-27 14:44

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'indexes': [models.Index(fields=['is_deleted', 'url'], name='idx_active_url')],
            },
        ),
    ]
